#!/usr/bin/ruby
source 'https://rubygems.org'
gem 'typhoeus'
gem 'json'
gem 'nokogiri'

gem 'pry'
gem 'pry-byebug'
gem 'pry-coolline'
gem 'pry-doc'
gem 'pry-git'
gem 'pry-inline'
gem 'pry-rescue'
gem 'pry-stack_explorer'
gem 'pry-state'
gem 'pry-syntax-hacks'
gem 'pry-theme'

gem 'celluloid'
gem 'celluloid-io'
gem 'websocket'
gem 'websocket-native'
gem 'http_parser.rb'

if Gem::Version.new(RUBY_VERSION) >= Gem::Version.new('2.2.2')
  gem 'http-2', :git => "https://github.com/slact/http-2.git"
  gem 'rack'
  gem "memory_profiler", :git => "https://github.com/slact/memory_profiler.git"
else
  gem 'rack', '~> 1.6.4'
end

gem 'reel', :git => "https://github.com/celluloid/reel.git"
gem 'reel-rack', :git => "https://github.com/slact/reel-rack.git"
  
gem 'minitest'
gem 'minitest-reporters'


gem 'fpm', :git => "https://github.com/slact/fpm.git"

gem 'hsss'
