#!/usr/bin/ruby
source 'https://rubygems.org'
gem 'rack'
gem 'typhoeus'
gem 'json'
gem 'nokogiri'
gem 'pry'
gem 'pry-debundle'
gem 'celluloid'
gem 'minitest'
gem 'minitest-reporters'
gem 'eventmachine'
gem 'websocket-eventmachine-client'
gem 'fpm', :github => "slact/fpm"
