#!/usr/bin/ruby
source 'https://rubygems.org'
gem 'typhoeus'
gem 'json'
gem 'oga'

gem 'irb'
gem 'pry'
gem 'rdoc'
gem 'pry-byebug'
gem 'pry-coolline'
gem 'pry-doc'
gem 'pry-git'
gem 'pry-inline'
gem 'pry-rescue'
#gem 'pry-stack_explorer'
#gem 'pry-state'
gem 'pry-syntax-hacks'
gem 'pry-theme'

gem 'celluloid', "~>0.17.4"
if Gem::Version.new(RUBY_VERSION) < Gem::Version.new('2.2.2')
  gem 'nio4r', '~>1.2.1'
end
gem 'celluloid-io'
gem 'nchan_tools', :path => "./nchan_tools-gem"
#gem "memory_profiler", :git => "https://github.com/slact/memory_profiler.git"

gem 'rack', "~> 2.2.4"
gem 'reel', :git => "https://github.com/celluloid/reel.git"
gem 'reel-rack', :git => "https://github.com/slact/reel-rack.git"
  
gem 'minitest'
gem 'minitest-reporters'


gem "async"
gem "async-io"
gem "async-http"
gem "async-websocket"
gem "falcon"
gem "async-await"
gem "thread-local"
gem "colorize"

gem 'fpm', :git => "https://github.com/slact/fpm.git"

gem 'hsss', "~> 0.1.23"
